### ISSUE TITLE
decompile: parse luac: Error( Stack { base: Alt( [ Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, ], ), contexts: [ ( 1093, Kind( Count, ), ), ( 1089, Context( "count constants", ), ), ( 821, Context( "chunk", ), ), ( 302, Kind( Count, ), ), ( 298, Context( "count prototypes", ), ), ( 75, Context( "chunk", ), ), ], }, )

### ISSUE THREAD

**Issue by Sigelo** [metaworm/luac-parser-rs#11]
decompile: parse luac: Error( Stack { base: Alt( [ Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, Base { location: 1360, kind: Kind( Tag, ), }, ], ), contexts: [ ( 1093, Kind( Count, ), ), ( 1089, Context( "count constants", ), ), ( 821, Context( "chunk", ), ), ( 302, Kind( Count, ), ), ( 298, Context( "count prototypes", ), ), ( 75, Context( "chunk", ), ), ], }, )

**Comment by metaworm** [comment]
This is an error in the luac parsing process.
Please ensure that your bytecode file is compiled through the official Luac. If not, you should write your custom luac parser and load it to decompiler. Refer to https://github.com/metaworm/luac-parser-rs/wiki/Write-custom-luac-parser
