### ISSUE TITLE
反编译 遇到表达式计算，出现结果错误

### ISSUE THREAD

**Issue by xxoo886** [metaworm/luac-parser-rs#12]
luajit反编译
源 :
print(160 * 160)
print(170 * 170)
print(180 * 180)
print(190 * 190)
print(200 * 200)
使用metaworm反编译结果：
print(25600)
print(28900)
print(32400)
print(429316) --正确结果 36100
print(932928) --正确结果 40000
似乎大于180 就会计算结果错误
-----------------------------------
同理：大于36100的值(具体值_未测试) ，直接反编译错误
源：
print(36100) or print(40000)
反编译结果：
print(429316) or print(932928)

**Comment by metaworm** [comment]
感谢反馈，已修复

**Comment by xxoo886** [comment]
我直接使用 网页反编译，依然错误， 使用最新的parser编译成WASM载入到网页  然后反编译，整数结果还是错误

**Comment by metaworm** [comment]
更新出了点问题。。你再试试

**Comment by xxoo886** [comment]
可以正常反编译整数值了，  还有一个问题， 网页反编译 一些luajit的时候 会一直转圈大概10秒 然后提示 Decompile timeout 是什么原因 
[test_timeout.zip](https://github.com/metaworm/luac-parser-rs/files/12832684/test_timeout.zip)

**Comment by metaworm** [comment]
有些错误处理不是很完善，我刚刚修复了一些问题；你提供的这份luac现在可以正常显示反编译结果了，多刷新几次网页再试试

**Comment by xxoo886** [comment]
还是数值问题，比如
print(var * -150)
反编译结果是
print(var * 4294967146)

**Comment by metaworm** [comment]
修了

**Comment by xxoo886** [comment]
有两份 luajit2.1.0-beta3的文件，两份文件都可以用官方的luajit2.1.0-beta3 正常运行。
 一份可以在网站上面正常反编译，一份好像是在里面插入了什么代码 ，导致网站不能反编译(识别是opcode被改了) 但是用官方的opcode也能正常运行lua文件
[dump.zip](https://github.com/user-attachments/files/15837276/dump.zip)
