### ISSUE TITLE
Invalid table argument lift

### ISSUE THREAD

**Issue by toxamin** [metaworm/luac-parser-rs#14]
When given the following script:
```
local t = { func("arg1", "arg2") }
```

Metaworm's luadec produces the following result:
```
local r0_0 = {
  func,
  "arg1",
  "arg2",
  r1_0(r2_0, r3_0)
}
```
It does lift all the arguments inside of the table, however forgets to call first.

**Comment by metaworm** [comment]
Thanks for your feedback, this is a bug.  I'll fix it as soon as possible.
