### ISSUE TITLE
关于lua文件不可识读

### ISSUE THREAD

**Issue by size404** [metaworm/luac-parser-rs#20]
报错decompile: parse luac: Error( Stack { base: Alt( [ Base { location: 98, kind: Kind( Switch, ), }, Base { location: 98, kind: Kind( Switch, ), }, Base { location: 98, kind: Kind( Switch, ), }, Base { location: 98, kind: Kind( Switch, ), }, ], ), contexts: [ ( 98, Context( "integer", ), ), ], }, )

**Comment by metaworm** [comment]
一般出现`parse luac:`的错误是由于用户选择了非标准格式的lua字节码文件，请确认你的字节码文件是否是通过官方lua编译的，没有被第三方修改过
