### ISSUE TITLE
疑似反编译器超时太小不够在我的场景下正常使用

### ISSUE THREAD

**Issue by RigoLigoRLC** [metaworm/luac-parser-rs#35]
![image](https://github.com/metaworm/luac-parser-rs/assets/49363666/bb897f10-cfd6-4bdd-bc76-2dede98d4e4c)

逆向时提取了一个102KB大小的luac编译块（没有调试信息，基本纯为constant和代码），有200多个函数，解析指令（右下角配置中勾选反汇编，然后打开luac文件）花去数秒，网页中写死的20s超时时间可能不足反编译完成。由于没有其他进度提示（比如显示出在某函数中卡死），无法判断具体情况。

**Comment by metaworm** [comment]
后面会增加自定义超时的选项
