### ISSUE TITLE
decompile: parse luac: Error( Stack

### ISSUE THREAD

**Issue by jjc6676** [metaworm/luac-parser-rs#40]
Getting an error message when trying to load file. These were working before.  Just wondering what I can do to get it working?
Any help would be greatly appreciated.

![Screenshot 2024-05-08 162631](https://github.com/metaworm/luac-parser-rs/assets/4475063/9a355973-2a16-4388-a48d-0d0d2e00f33e)

**Comment by toxamin** [comment]
perhaps you should send the file so the issue can be debugged? :D

**Comment by jjc6676** [comment]
[card.zip](https://github.com/metaworm/luac-parser-rs/files/15382817/card.zip)

Thank you for the suggestion @toxamin

**Comment by toxamin** [comment]
note, should you wish to decompile the file yourself all you need to do is simply remove the extra 8 bytes, which are shown in the screenshot:
![image](https://github.com/metaworm/luac-parser-rs/assets/30242831/c1e93822-6567-4756-bb46-885c27c92c6c)

**Comment by jjc6676** [comment]
This is most excellent and I appreciate your hard work. Can you tell me which program I can use to remove the extra bytes?
VS Studio? Pulsar? or something else? I apologize as I am still learning.

Thank you in advance!

**Comment by jjc6676** [comment]
I learned that I need to use a hex editor @toxamin 
The part above highlighted in the second part with the $ symbol... Do I need to delete that as well?

**Comment by jjc6676** [comment]
I figured it all out - sorry for the questions. Thank you so much!
