### ISSUE TITLE
解析lua编译后文件报下面的错表示什么意思？

### ISSUE THREAD

**Issue by tenvick** [metaworm/luac-parser-rs#49]
decompile: parse luac: Error( Alt( [ Base { location: 4, kind: Kind( Tag, ), }, Base { location: 4, kind: Kind( Tag, ), }, Base { location: 4, kind: Kind( Tag, ), }, Base { location: 4, kind: Kind( Tag, ), }, Base { location: 0, kind: Kind( Tag, ), }, ], ), )

**Comment by metaworm** [comment]
字节码文件格式有问题
