### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by ona2000rblx** [metaworm/luac-parser-rs#59]
The site was working completely fine yesterday, but it seems to have had its SSL certificate expired today. 

When you try to decompile a lua file you get this error:
`decompile: connect: Failed to connect to the server. CloseEvent: CloseEvent { code: 1006, reason: "", was_clean: false }`

Hope this is resolved asap!

**Comment by Scripteri** [comment]
Yeah @metaworm  fix this please

**Comment by ona2000rblx** [comment]
Site seems to be up and working again!
