### ISSUE TITLE
Issue with decompiling lua 5.4

### ISSUE THREAD

**Issue by ona2000rblx** [metaworm/luac-parser-rs#60]
Not sure what happened but with the new change to the parser, arrays for lua 5.4 files are now incorrect.
The arrays are now split with an error comment,  `-- setlist for #4 failed`

There were no issues prior to the site outage when decompiling lua 5.4 files.

**Comment by riyanurpradana** [comment]
"I totally agree! I also prefer the previous version. It was much more stable and easier to work with. I hope they consider restoring it soon."

**Comment by metaworm** [comment]
I have now switched to the previous version. #62

**Comment by ona2000rblx** [comment]
It seems to be working as intended now. Thank you for all the work!
