### ISSUE TITLE
是否可以考虑支持OpenWRT中的lua反编译

### ISSUE THREAD

**Issue by Lua12138** [metaworm/luac-parser-rs#7]
OpenWRT中对于lua有一些魔改，同时不同版本也有一些不同，例如：

https://github.com/thejuan/OpenWrt-14.07/tree/master/package/utils/lua/patches
https://github.com/openwrt/openwrt/tree/master/package/utils/lua/patches

**Comment by metaworm** [comment]
从你发的patch diff来看，OpenWRT对luac文件格式的修改不大，主要是对跨架构（32位/64未、大小端）的支持

另外我好像没看到对header部分的区别，也就是说无法通过header来区分一个luac是官方格式的还是OpenWRT的，所以不太好合入现有代码

如果你有反编译的需求，可以尝试修改 https://github.com/metaworm/luac-parser-rs/blob/master/src/lua51.rs 中的一小部分代码来加载自己的parser，对openwrt进行兼容；可以参考一下这个项目 https://github.com/metaworm/openwrt-luac-parser
