### ISSUE TITLE
luajit goto 寻求大佬帮助

### ISSUE THREAD

**Issue by flyqie** [metaworm/luac-parser-rs#8]
大佬好, 感谢您开源该项目.

目前有个luajit过的文件含有goto, 分析的时候提示`error: decompile function#1 panic: index out of bounds: the len is 12 but the index is 25`, 个人能力有限, 实在是摸不清头脑.

能麻烦您帮忙看一下嘛?

感谢.

[luajit_file.zip](https://github.com/metaworm/luac-parser-rs/files/12332050/luajit_file.zip)

**Comment by metaworm** [comment]
你可以看一下字节码，最后一条指令`Jump r4, 1; -> 9`跳到了9的指令位置，但一共才7条指令，有没有可能是字节码被篡改过了？

<pre>[0]	MOV r3 = r1<br>[1]	TGETS r2 = r1, r0	; "getBody"<br>[2]	Call r2, r2, r2<br>[3]	MOV r4 = r1<br>[4]	TGETS r3 = r1, r1	; "getType"<br>[5]	Call r3, r2, r2<br>[6]	IST r0, r3<br>[7]	Jump r4, 1; -&gt; 9<br></pre>

你提到这个文件含有goto，有源码吗? 或许是我解析的问题，如果有源码我可以调一下看看

**Comment by flyqie** [comment]
> 你可以看一下字节码，最后一条指令`Jump r4, 1; -> 9`跳到了9的指令位置，但一共才7条指令，有没有可能是字节码被篡改过了？
> 
> [0]	MOV r3 = r1
> [1]	TGETS r2 = r1, r0	; "getBody"
> [2]	Call r2, r2, r2
> [3]	MOV r4 = r1
> [4]	TGETS r3 = r1, r1	; "getType"
> [5]	Call r3, r2, r2
> [6]	IST r0, r3
> [7]	Jump r4, 1; -> 9
> 你提到这个文件含有goto，有源码吗? 或许是我解析的问题，如果有源码我可以调一下看看

感谢大佬回复。

这个文件是碧蓝航线最开始公测时候的客户端lua代码，个人想看看碧蓝航线最开始公测的时候在代码上与现在有多大差别(现在的代码已经有其他大佬反编译出来了，似乎是正常的，不知道是怎么回事https://github.com/AzurLaneTools/AzurLaneLuaScripts/blob/main/CN/controller/command/state/gobackcommand.lua)。

使用https://github.com/AzurLaneTools/ljd反编译其他文件都很正常，唯独这个文件提示`AssertionError('GOTO statements are not supported')` ，所以按照提示猜测可能是goto问题导致的。。

**Comment by flyqie** [comment]
> 你可以看一下字节码，最后一条指令`Jump r4, 1; -> 9`跳到了9的指令位置，但一共才7条指令，有没有可能是字节码被篡改过了？
> 
> [0]	MOV r3 = r1
> [1]	TGETS r2 = r1, r0	; "getBody"
> [2]	Call r2, r2, r2
> [3]	MOV r4 = r1
> [4]	TGETS r3 = r1, r1	; "getType"
> [5]	Call r3, r2, r2
> [6]	IST r0, r3
> [7]	Jump r4, 1; -> 9
> 你提到这个文件含有goto，有源码吗? 或许是我解析的问题，如果有源码我可以调一下看看

感谢大佬回复。

这个文件是AzurLane最开始公测时候的客户端lua代码，个人想看看AzurLane最开始公测的时候在代码上与现在有多大差别(现在的代码已经有其他大佬反编译出来了，似乎是正常的，不知道是怎么回事[gobackcommand.lua](https://github.com/AzurLaneTools/AzurLaneLuaScripts/blob/main/CN/controller/command/state/gobackcommand.lua)。)

使用[AzurLaneTools/ljd](https://github.com/AzurLaneTools/ljd)反编译其他文件都很正常，唯独这个文件提示`AssertionError('GOTO statements are not supported')` ，所以按照提示猜测可能是goto问题导致的。。

**Comment by marsinator358** [comment]
Hello,

I've tried your file with my own decompiler and it turns out there is a break statement which breaks the python decompiler.
Here is the output which I decompiled by hand (may contain errors):

```
local var_0_0 = class(GoBackCommand, pm.SimpleCommand)

function var_0_0.execute(arg_1_0, arg_1_1)
	local var_1_2 = arg_1_1:getBody()
	local var_1_3 = arg_1_1:getType() or 1
	local var_1_4 = getProxy(ContextProxy)

	if var_1_4:getContextCount() > 1 then
		local var_1_5 = var_1_4:popContext()
		local var_1_6

		for iter_1_10 = 1, var_1_3 do
			repeat
				if var_1_4:getContextCount() > 0 then
					var_1_6 = var_1_4:popContext()
				else
					print("could not pop more context")
					break -- note: causes error with python decompiler
				end
			until not var_1_6.ignoreBack
		end

		var_1_6:extendData(var_1_2)
		arg_1_0:sendNotification(GAME.LOAD_SCENE, { prevContext = var_1_5, context = var_1_6 })
	else
		print("no more context in the stack")
	end
end

return var_0_0
```

**Comment by flyqie** [comment]
> 

Thank you very much for your help, this solved my doubt perfectly.

**Comment by flyqie** [comment]
> Hello,
> 
> I've tried your file with my own decompiler and as it turns out there is a break statement which breaks the python decompiler. Here is the output which I decompiled by hand (may contain errors):
> 
> ```
> local var_0_0 = class(GoBackCommand, pm.SimpleCommand)
> 
> function var_0_0.execute(arg_1_0, arg_1_1)
> 	local var_1_2 = arg_1_1:getBody()
> 	local var_1_3 = arg_1_1:getType() or 1
> 	local var_1_4 = getProxy(ContextProxy)
> 
> 	if var_1_4:getContextCount() > 1 then
> 		local var_1_5 = var_1_4:popContext()
> 		local var_1_6
> 
> 		for iter_1_10 = 1, var_1_3 do
> 			repeat
> 				if var_1_4:getContextCount() > 0 then
> 					var_1_6 = var_1_4:popContext()
> 				else
> 					print("could not pop more context")
> 					break -- note: causes error with python decompiler
> 				end
> 			until not var_1_6.ignoreBack
> 		end
> 
> 		var_1_6:extendData(var_1_2)
> 		arg_1_0:sendNotification(GAME.LOAD_SCENE, { prevContext = var_1_5, context = var_1_6 })
> 	else
> 		print("no more context in the stack")
> 	end
> end
> 
> return var_0_0
> ```

Thank you very much for your help, this solved my doubt perfectly.
